class Selectors:
    EMAIL = "//*[@id='ap_email']"
    CONTINUE_BUTTON = "//*[contains(@class, 'a-button-input')]"
    PASSWORD = "//*[@id='ap_password']"
    SIGNIN_BUTTON = "//*[@id='signInSubmit']"
    SEARCH_BOX = "//*[@id='twotabsearchtextbox']"
    SEARCH_SUBMIT = "//input[@id='nav-search-submit-button']"
    SEARCH_ITEM = "//span[@data-component-type='s-search-results']/div[2]/div[3]"
    ADD_TO_CART = "//*[@id='add-to-cart-button']"
    BUY = "//*[@id='hlb-ptc-btn-native']"
    FULL_NAME = "//input[@id='address-ui-widgets-enterAddressFullName']"
    PHONE_NUMBER = "//input[@id='address-ui-widgets-enterAddressPhoneNumber']"
    POSTAL_CODE = "//input[@id='address-ui-widgets-enterAddressPostalCode']"
    APARTMENT = "//input[@id='address-ui-widgets-enterAddressLine1']"
    AREA = "//input[@id='address-ui-widgets-enterAddressLine2']"
    LANDMARK = "//input[@id='address-ui-widgets-landmark']"
    CITY = "//input[@id='address-ui-widgets-enterAddressCity']"
